# Generated by Django 3.2.9 on 2021-11-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Username', models.CharField(max_length=40)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
